# Unix (Linux/macOS) configuration
# This file is included from local.toml

[nvim.files]
"packages/nvim" = "~/.config/nvim"

[alacritty.files]
"packages/alacritty/alacritty.toml.tmpl" = { type = "template", target = "~/.config/alacritty/alacritty.toml" }
"packages/alacritty/themes" = { type = "symbolic", target = "~/.config/alacritty/themes" }

[wezterm.files]
"packages/wezterm" = "~/.config/wezterm"

[zsh.files]
"packages/zsh/.zshrc" = "~/.zshrc"
"packages/zsh/conf.d" = "~/.config/zsh/conf.d"

[tmux.files]
"packages/tmux/.tmux.conf" = "~/.tmux.conf"
"packages/tmux/conf.d" = "~/.tmux.d"
